// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFQeuY_JWbNzC0r_PNHLD5Q37PYwWlNyw',
    appId: '1:702786780990:web:24791858b058dd7ccc766f',
    messagingSenderId: '702786780990',
    projectId: 'tapp-6e74a',
    authDomain: 'tapp-6e74a.firebaseapp.com',
    storageBucket: 'tapp-6e74a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD6dHd_YZUR7akDJfNGXlUOFeCCHCBH9I',
    appId: '1:702786780990:android:6efb85f9a391a6ddcc766f',
    messagingSenderId: '702786780990',
    projectId: 'tapp-6e74a',
    storageBucket: 'tapp-6e74a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd2wGVrSqA0IROMow6be7L1OPd1J_wYZw',
    appId: '1:702786780990:ios:4cb04956046b92dfcc766f',
    messagingSenderId: '702786780990',
    projectId: 'tapp-6e74a',
    storageBucket: 'tapp-6e74a.firebasestorage.app',
    iosBundleId: 'com.example.tapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd2wGVrSqA0IROMow6be7L1OPd1J_wYZw',
    appId: '1:702786780990:ios:4cb04956046b92dfcc766f',
    messagingSenderId: '702786780990',
    projectId: 'tapp-6e74a',
    storageBucket: 'tapp-6e74a.firebasestorage.app',
    iosBundleId: 'com.example.tapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFQeuY_JWbNzC0r_PNHLD5Q37PYwWlNyw',
    appId: '1:702786780990:web:b0c0cf918ecefac7cc766f',
    messagingSenderId: '702786780990',
    projectId: 'tapp-6e74a',
    authDomain: 'tapp-6e74a.firebaseapp.com',
    storageBucket: 'tapp-6e74a.firebasestorage.app',
  );

}